spring.application.name=waterReportSystem-backend

spring.datasource.url=jdbc:mysql://localhost:3306/water_report_system_db
spring.datasource.username=root
spring.datasource.password=Mola11.#0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
jwt.secret=waterwatch-super-secret-jwt-key-that-is-long-enough-2026
jwt.expiration=86400000
server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mokotedikgalalelo93@gmail.com
spring.mail.password=mxsvmcjqgpmefwzj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
